apiVersion: apps/v1
kind: Deployment
metadata:
  name: skeleton
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skeleton
  template:
    metadata:
      labels:
        app: skeleton
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: api
          image: tpmacc/skeleton
          imagePullPolicy: Always
          ports:
            - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: skeleton
  annotations:
    dev.okteto.com/auto-ingress: "true"
  labels:
    app: skeleton
spec:
  type: ClusterIP
  ports:
    - name: skeleton
      port: 9001
  selector:
    app: skeleton