apiVersion: v1
kind: Service
metadata:
  name: skeleton-svc
  labels:
    app: skeleton
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skeleton
  labels:
    app: skeleton
spec:
  replicas: 3
  selector:
    matchLabels:
      app: skeleton
  template:
    metadata:
      labels:
        app: skeleton
    spec:
      containers:
        - name: skeleton
          image: nginx:1.14.2
          ports:
            - containerPort: 80
