spring:
  application:
    name: skeleton

server:
  port: 9001

# expose actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
    info:
      enabled: true

# configure span reporter
opentracing:
  jaeger:
    udp-sender:
      host: localhost
      port: 6831

skel:
  envvar: "application.yaml"